enum DocKeyPhotoMemo { name, memo, createdBy, quantity }

class Inventory {
  String? docId; // generated by Firestore
  String createdBy; // email
  String name;
  int quantity;

  Inventory({
    this.docId,
    required this.createdBy,
    required this.name,
    required this.quantity,
  });

  static String? validateName(String? value) {
    String? lowerCase = value?.toLowerCase();
    return value == null || value.trim().length < 2 ? 'Title too short' : null;
  }

  // static int? validateQuantity(int? value) {
  //   // return value == null || value.trim().length < 7 ? 'Memo too short' : null;
  // }
}
