import 'package:lesson6/controller/firestore_controller.dart';

enum DocKeyPhotoMemo { title, createdBy, quantity }

class Inventory {
  String? docId; // generated by Firestore
  String createdBy; // email
  String title;
  String quantity;

  Inventory({
    this.docId,
    required this.createdBy,
    required this.title,
    required this.quantity,
  });

  factory Inventory.fromFirestoreDoc({
    required Map<String, dynamic> doc,
    required String docId,
  }) {
    return Inventory(
      docId: docId,
      createdBy: doc[DocKeyPhotoMemo.createdBy.name] ?? '',
      title: doc[DocKeyPhotoMemo.title.name] ?? '',
      quantity: doc[DocKeyPhotoMemo.quantity.name] ?? '',
    );
  }

  Map<String, dynamic> toFirestoreDoc() {
    return {
      DocKeyPhotoMemo.title.name: title,
      DocKeyPhotoMemo.createdBy.name: createdBy,
      DocKeyPhotoMemo.quantity.name: quantity,
    };
  }

  static String? validateTitle(String? value, List<Inventory> inventoryList) {
    return value == null || value.trim().length < 2 ? 'Title too short' : null;
  }
}
