// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIuOqyIPVQ4lSyJZNHh1KD8VvDDhrLZK8',
    appId: '1:203414158908:web:d8712e260371b63bdf8d39',
    messagingSenderId: '203414158908',
    projectId: 'ywong8-cmsc4303-flutter',
    authDomain: 'ywong8-cmsc4303-flutter.firebaseapp.com',
    storageBucket: 'ywong8-cmsc4303-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpZN-A8ZHNCJcD0J6dxoHOIOYgtU1RJ0I',
    appId: '1:203414158908:android:f95f4edbba9dc9b4df8d39',
    messagingSenderId: '203414158908',
    projectId: 'ywong8-cmsc4303-flutter',
    storageBucket: 'ywong8-cmsc4303-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6ulAqcssE3or32D5Wx5IK4POJHVL4r14',
    appId: '1:203414158908:ios:2675941c680c1808df8d39',
    messagingSenderId: '203414158908',
    projectId: 'ywong8-cmsc4303-flutter',
    storageBucket: 'ywong8-cmsc4303-flutter.appspot.com',
    iosBundleId: 'edu.uco.ywong8.cmsc4303.lesson6',
  );
}
